const invalidCards = ['(MTO) Hwy 417 near Innes Rd', 'Cyrville & Innes', 'Highway 417 (West) & Innes', 'Innes & Bearbrook', 'Innes & Blackburn Hamlet Bypass', 'Heron & Riverside', 'Riverside & Tremblay', 'Fallowfield & Prince of Wales', 'Baseline & Merivale', 'Cummings & Ogilvie', '(MTO) Hwy 417 west of Holly Acres Rd', '(MTO) Hwy 417 west of Moodie Drive', '(MTO) Hwy 417 west of Moodie Drive', '(MTO) Hwy 417 west of Holly Acres Rd', 'Bank & Hunt Club', 'Castlefrank & Hazeldean', '(MTO) Hwy 417 near Walkley Rd', '(MTO) Hwy 417 near Vanier Parkway', '(MTO) Hwy 417 near Terry Fox Drive', 'Pinecrest & Richmond', 'Orleans & St. Joseph', 'Parkdale & Scott'];

const moreInvalidCards = ['(MTO) Hwy 417 near St Laurent Blvd', '(MTO) Hwy 417 near Palladium Drive', "(MTO) Hwy 417 near O'Connor St", '(MTO) Hwy 417 near Moodie Drive', '(MTO) Hwy 417 near Kanata Ave', '(MTO) Hwy 417 near Hwy 7', '(MTO) Hwy 417 near Eagleson Rd', '(MTO) Hwy 417 near Carp Rd', '(MTO) Hwy 417 near Bronson Ave', '(MTO) Hwy 417 Near Belfast Rd', '(MTO) Hwy 417 near Bayswater Ave', '(MTO) Hwy 417 near Aviation Parkway', '(MTO) Hwy 417 east of Moodie Drive', '(MTO) Hwy 417 east of Eagleson Rd', '(MTO) Hwy 416 NB ramp to Hwy 417 East', 'Bayview & Scott', 'Clegg & Colonel By', 'Fifth and Queens Elizabeth Driveway', "Highway 174 & Jeanne D'Arc", 'Holland & Wellington', 'Hunt Club & Lowes', 'Hunt Club & Uplands', 'Kent & Queen', 'Kent & Slater', 'Lemieux & St Laurent', 'Main & Clegg', 'Main & Riverdale', 'Montreal & Aviation', 'Montreal & Aviation', 'Montreal & Shefford', 'Orleans & St. Joseph', 'Parkdale & Scott', "Place d'Orleans & St. Joseph", 'Montreal & Blair'];

const evenMoreInvalidCards = ['Highway 174 (East) at Blair', 'Highway 174 east of Blair', 'Highway 174 east of Montreal', 'Highway 174 west of Blair', 'Highway 417 (East) & St Laurent', 'Highway 417 (West) & Maitland', 'Industrial & Trainyards', 'Laurier & Transitway', 'McKenna Casey near Strandherd', 'Russell & Walkley', 'Sir John A. Macdonald Parkway & Vimy', 'Smyth & Hospital', 'St. Laurent & Walkley', "Albert & O'Connor", 'Albion & Leitrim', 'Algonquin & Woodroffe', 'Alta Vista & Heron', 'Alta Vista & Industrial', 'Baseline & Fisher', 'Baseline & Richmond', 'Boteler & Sussex', 'Bronson & Somerset', 'Carling & Holland', "Catherine & O'Connor", 'Cumberland & Laurier', 'Donald & St. Laurent', 'Eagleson & Katimavik/Timm', 'Eagleson & Michael Cowpland/Stonehaven', 'Elgin & Gladstone', 'Foxfield & Greenbank', 'Gilligan & Leitrim', 'Greenbank & Berrigan/Wessex', 'Greenbank & Hunt Club', 'Slack & Woodroffe', 'Greenfield & Main', 'Hawthorne & Main', 'Hazeldean & Huntmar'];

const invalidCardInstance = moreInvalidCards.concat(evenMoreInvalidCards);
const notWorkingCards = invalidCards.concat(invalidCardInstance);

module.exports = {notWorkingCards};
